##### [START] CATALINA HOME CONFIG IN DEVELOPMENT/ PRODUCTION [/START] ########
## Note: ENABLE THIS ONLY IN CASE OF EMBEDDED TOMCAT DEPLOYMENT  ###
######___ ***** ENTER PATH TO YOUR STAND-ALONE TOMCAT SERVER ***** ____ ############

#catalina:
#  home: Path/to/your/external/tomcat

#catalina:
#  home: /home/rupak/Softwares/tomcat

##### [END] CATALINA HOME CONFIG [/END] #########

spring:
  profiles:
    active: uat
